export const dish = [
    { value: "1", icon: "aperitif", label: "Aperitif" },
    { value: "2", icon: "appetizer", label: "Appetizer" },
    { value: "3", icon: "chicken", label: "Drób" },
    { value: "4", icon: "ciasta", label: "Ciasta" },
    { value: "5", icon: "cow", label: "Wołowina" },
    { value: "6", icon: "deer", label: "Dziczyzna" },
    { value: "7", icon: "digestif", label: "Digestif" },
    { value: "8", icon: "ewe", label: "Baranina" },
    { value: "9", icon: "fish", label: "Ryby" },
    { value: "10", icon: "fruits", label: "Owoce" },
    { value: "11", icon: "ice-cream", label: "Lody" },
    { value: "12", icon: "mushroom", label: "Grzyby" },
    { value: "13", icon: "deser", label: "Desery" },
    { value: "14", icon: "pasta", label: "Makarony" },
    { value: "15", icon: "plesniowy", label: "Sery pleśniowe" },
    { value: "16", icon: "pork", label: "Wieprzowina" },
    { value: "17", icon: "risotto", label: "Risotto" },
    { value: "18", icon: "salad", label: "Sałatki" },
    { value: "19", icon: "sery-delikatne", label: "Sery delikatne" },
    { value: "20", icon: "sery-slone", label: "Sery słone" },
    { value: "21", icon: "sery-twarde", label: "Sery twarde" },
    { value: "22", icon: "shrimp", label: "Owoce morza" },
    { value: "23", icon: "sushi", label: "Kuchnia orientalna" },
    { value: "24", icon: "tarta", label: "Tarty" },
    { value: "25", icon: "walnut", label: "Orzechy" },
    { value: "26", icon: "zupa", label: "Zupy" },
  ];

export default { dish };