import {
Al,Dz,As,Ad,Ao,Ai,Ag,Ar,Am,Aw,Au,At,Az,Bs,Bh,Bd,Bb,By,Be,Bz,Bj,Bm,Bt,Bo,Ba,Bw,Br,Io,Bg,Bf,Bi,Kh,Cm,Ca,Cv,Ky,Cf,Td,Cl,Cn,Co,Km,Cg,Cd,Ck,Cr,Ci,Hr,Cu,Cw,Cy,Cz,Dk,Dj,Dm,Do,Ec,Eg,Sv,Gq,Er,Ee,Et,Fk,Fo,Fj,Fi,Fr,Pf,Ga,Gm,Ge,De,Gh,Gi,Gr,Gl,Gd,Gu,Gt,Gg,Gn,Gw,Ht,Hn,Hk,Hu,Is,In,Id,Ir,Iq,Ie,Im,Il,It,Jm,Jp,Je,Jo,Kz,Ke,Ki,Kp,Kr,Kw,Kg,La,Lv,Lb,Ls,Lr,Ly,Li,Lt,Lu,Mo,Mk,Mg,Mw,My,Mv,Ml,Mt,Mh,Mq,Mr,Mu,Mx,Fm,Md,Mc,Mn,Me,Ms,Ma,Mz,Mm,Na,Nr,Np,Nl,Nz,Ni,Ne,Ng,Nu,Nf,Mp,No,Om,Pk,Pw,Ps,Pa,Pg,Py,Pe,Ph,Pn,Pl,Pt,Pr,Qa,Ro,Ru,Rw,Kn,Lc,Ws,Sm,St,Sa,Sn,Rs,Sc,Sl,Sg,Sx,Sk,Si,Sb,So,Za,Ss,Es,Lk,Sd,Sr,Sz,Se,Ch,Sy,Tw,Tj,Tz,Th,Tg,Tk,To,Tt,Tn,Tr,Tm,Tc,Tv,Ug,Ua,Ae,Gb,Us,Uy,Uz,Vu,Ve,Vn,Vi,Ye,Zm,Zw 
   } from "react-flags-select";

export const flags = [
    { value: "Al", icon:<Al/>, label: "Albania" },
    { value: "Dz", icon:<Dz/>, label: "Algeria" },
    { value: "As", icon:<As/>, label: "Samoa Amerykańskie" },
    { value: "Ad", icon:<Ad/>, label: "Andora" },
    { value: "Ao", icon:<Ao/>, label: "Angola" },
    { value: "Ai", icon:<Ai/>, label: "Anguilla" },
    { value: "Ag", icon:<Ag/>, label: "Antigua i Barbuda" },
    { value: "Ar", icon:<Ar/>, label: "Argentyna" },
    { value: "Am", icon:<Am/>, label: "Armenia" },
    { value: "Aw", icon:<Aw/>, label: "Aruba" },
    { value: "Au", icon:<Au/>, label: "Australia" },
    { value: "At", icon:<At/>, label: "Austria" },
    { value: "Az", icon:<Az/>, label: "Azerbejdżan" },
    { value: "Bs", icon:<Bs/>, label: "Bahamy" },
    { value: "Bh", icon:<Bh/>, label: "Bahrajn" },
    { value: "Bd", icon:<Bd/>, label: "Bangladesz" },
    { value: "Bb", icon:<Bb/>, label: "Barbados" },
    { value: "By", icon:<By/>, label: "Białoruś" },
    { value: "Be", icon:<Be/>, label: "Belgia" },
    { value: "Bz", icon:<Bz/>, label: "Belize" },
    { value: "Bj", icon:<Bj/>, label: "Benin" },
    { value: "Bm", icon:<Bm/>, label: "Bermudy" },
    { value: "Bt", icon:<Bt/>, label: "Bhutan" },
    { value: "Bo", icon:<Bo/>, label: "Boliwia" },
    { value: "Ba", icon:<Ba/>, label: "Bośnia i Hercegowina" },
    { value: "Bw", icon:<Bw/>, label: "Botswana" },
    { value: "Br", icon:<Br/>, label: "Brazylia" },
    { value: "Io", icon:<Io/>, label: "Brytyjskie Teryt. O. Indyjsk." },
    { value: "Bg", icon:<Bg/>, label: "Bułgaria" },
    { value: "Bf", icon:<Bf/>, label: "Burkina Faso" },
    { value: "Bi", icon:<Bi/>, label: "Burundi" },
    { value: "Kh", icon:<Kh/>, label: "Kambodża" },
    { value: "Cm", icon:<Cm/>, label: "Kamerun" },
    { value: "Ca", icon:<Ca/>, label: "Kanada" },
    { value: "Cv", icon:<Cv/>, label: "Zielony Przylądek" },
    { value: "Ky", icon:<Ky/>, label: "Kajmany" },
    { value: "Cf", icon:<Cf/>, label: "Rep. Środkowoafrykańska" },
    { value: "Td", icon:<Td/>, label: "Czad" },
    { value: "Cl", icon:<Cl/>, label: "Chile" },
    { value: "Cn", icon:<Cn/>, label: "Chiny" },
    { value: "Co", icon:<Co/>, label: "Kolumbia" },
    { value: "Km", icon:<Km/>, label: "Komory" },
    { value: "Cg", icon:<Cg/>, label: "Kongo" },
    { value: "Cd", icon:<Cd/>, label: "Rep. Demokratyczna Kongo" },
    { value: "Ck", icon:<Ck/>, label: "Wyspy Cooka" },
    { value: "Cr", icon:<Cr/>, label: "Kostaryka" },
    { value: "Ci", icon:<Ci/>, label: "Wybrzeże Kości Słoniowej" },
    { value: "Hr", icon:<Hr/>, label: "Chorwacja" },
    { value: "Cu", icon:<Cu/>, label: "Kuba" },
    { value: "Cw", icon:<Cw/>, label: "Kurakao" },
    { value: "Cy", icon:<Cy/>, label: "Cypr" },
    { value: "Cz", icon:<Cz/>, label: "Czechy" },
    { value: "Dk", icon:<Dk/>, label: "Dania" },
    { value: "Dj", icon:<Dj/>, label: "Dżibuti" },
    { value: "Dm", icon:<Dm/>, label: "Dominika" },
    { value: "Do", icon:<Do/>, label: "Dominikana" },
    { value: "Ec", icon:<Ec/>, label: "Ekwador" },
    { value: "Eg", icon:<Eg/>, label: "Egipt" },
    { value: "Sv", icon:<Sv/>, label: "Salwador" },
    { value: "Gq", icon:<Gq/>, label: "Gwinea Równikowa" },
    { value: "Er", icon:<Er/>, label: "Erytrea" },
    { value: "Ee", icon:<Ee/>, label: "Estonia" },
    { value: "Et", icon:<Et/>, label: "Etiopia" },
    { value: "Fk", icon:<Fk/>, label: "Falklandy" },
    { value: "Fo", icon:<Fo/>, label: "Wyspy Owcze" },
    { value: "Fj", icon:<Fj/>, label: "Fidżi" },
    { value: "Fi", icon:<Fi/>, label: "Finlandia" },
    { value: "Fr", icon:<Fr/>, label: "Francja" },
    { value: "Pf", icon:<Pf/>, label: "Polinezja Francuska" },
    { value: "Ga", icon:<Ga/>, label: "Gabon" },
    { value: "Gm", icon:<Gm/>, label: "Gambia" },
    { value: "Ge", icon:<Ge/>, label: "Gruzja" },
    { value: "De", icon:<De/>, label: "Niemcy" },
    { value: "Gh", icon:<Gh/>, label: "Ghana" },
    { value: "Gi", icon:<Gi/>, label: "Gibraltar" },
    { value: "Gr", icon:<Gr/>, label: "Grecja" },
    { value: "Gl", icon:<Gl/>, label: "Grenlandia" },
    { value: "Gd", icon:<Gd/>, label: "Grenada" },
    { value: "Gu", icon:<Gu/>, label: "Guam" },
    { value: "Gt", icon:<Gt/>, label: "Gwatemala" },
    { value: "Gg", icon:<Gg/>, label: "Guernsey" },
    { value: "Gn", icon:<Gn/>, label: "Gwinea" },
    { value: "Gw", icon:<Gw/>, label: "Gwinea-Bissau" },
    { value: "Ht", icon:<Ht/>, label: "Haiti" },
    { value: "Hn", icon:<Hn/>, label: "Honduras" },
    { value: "Hk", icon:<Hk/>, label: "Hongkong" },
    { value: "Hu", icon:<Hu/>, label: "Węgry" },
    { value: "Is", icon:<Is/>, label: "Islandia" },
    { value: "In", icon:<In/>, label: "Indie" },
    { value: "Id", icon:<Id/>, label: "Indonezja" },
    { value: "Ir", icon:<Ir/>, label: "Iran" },
    { value: "Iq", icon:<Iq/>, label: "Irak" },
    { value: "Ie", icon:<Ie/>, label: "Irlandia" },
    { value: "Im", icon:<Im/>, label: "Isle of Man" },
    { value: "Il", icon:<Il/>, label: "Izrael" },
    { value: "It", icon:<It/>, label: "Włochy" },
    { value: "Jm", icon:<Jm/>, label: "Jamajka" },
    { value: "Jp", icon:<Jp/>, label: "Japonia" },
    { value: "Je", icon:<Je/>, label: "Jersey" },
    { value: "Jo", icon:<Jo/>, label: "Jordania" },
    { value: "Kz", icon:<Kz/>, label: "Kazachstan" },
    { value: "Ke", icon:<Ke/>, label: "Kenia" },
    { value: "Ki", icon:<Ki/>, label: "Kiribati" },
    { value: "Kp", icon:<Kp/>, label: "Korea Północna" },
    { value: "Kr", icon:<Kr/>, label: "Korea Południowa" },
    { value: "Kw", icon:<Kw/>, label: "Kuwejt" },
    { value: "Kg", icon:<Kg/>, label: "Kirgistan" },
    { value: "La", icon:<La/>, label: "Laos" },
    { value: "Lv", icon:<Lv/>, label: "Łotwa" },
    { value: "Lb", icon:<Lb/>, label: "Liban" },
    { value: "Ls", icon:<Ls/>, label: "Lesotho" },
    { value: "Lr", icon:<Lr/>, label: "Liberia" },
    { value: "Ly", icon:<Ly/>, label: "Libia" },
    { value: "Li", icon:<Li/>, label: "Liechtenstein" },
    { value: "Lt", icon:<Lt/>, label: "Litwa" },
    { value: "Lu", icon:<Lu/>, label: "Luksemburg" },
    { value: "Mo", icon:<Mo/>, label: "Makau" },
    { value: "Mk", icon:<Mk/>, label: "Macedonia Północna" },
    { value: "Mg", icon:<Mg/>, label: "Madagaskar" },
    { value: "Mw", icon:<Mw/>, label: "Malawi" },
    { value: "My", icon:<My/>, label: "Malezja" },
    { value: "Mv", icon:<Mv/>, label: "Malediwy" },
    { value: "Ml", icon:<Ml/>, label: "Mali" },
    { value: "Mt", icon:<Mt/>, label: "Malta" },
    { value: "Mh", icon:<Mh/>, label: "Wyspy Marshalla" },
    { value: "Mq", icon:<Mq/>, label: "Martynikae" },
    { value: "Mr", icon:<Mr/>, label: "Mauretania" },
    { value: "Mu", icon:<Mu/>, label: "Mauritius" },
    { value: "Mx", icon:<Mx/>, label: "Meksyk" },
    { value: "Fm", icon:<Fm/>, label: "Mikronezja" },
    { value: "Md", icon:<Md/>, label: "Mołdawia" },
    { value: "Mc", icon:<Mc/>, label: "Monako" },
    { value: "Mn", icon:<Mn/>, label: "Mongolia" },
    { value: "Me", icon:<Me/>, label: "Czarnogóra" },
    { value: "Ms", icon:<Ms/>, label: "Montserrat" },
    { value: "Ma", icon:<Ma/>, label: "Maroko" },
    { value: "Mz", icon:<Mz/>, label: "Mozambik" },
    { value: "Mm", icon:<Mm/>, label: "Myanmar" },
    { value: "Na", icon:<Na/>, label: "Namibia" },
    { value: "Nr", icon:<Nr/>, label: "Nauru" },
    { value: "Np", icon:<Np/>, label: "Nepal" },
    { value: "Nl", icon:<Nl/>, label: "Holandia" },
    { value: "Nz", icon:<Nz/>, label: "Nowa Zelandia" },
    { value: "Ni", icon:<Ni/>, label: "Nikaragua" },
    { value: "Ne", icon:<Ne/>, label: "Niger" },
    { value: "Ng", icon:<Ng/>, label: "Nigeria" },
    { value: "Nu", icon:<Nu/>, label: "Niue" },
    { value: "Nf", icon:<Nf/>, label: "Norfolk" },
    { value: "Mp", icon:<Mp/>, label: "Mariany Północne" },
    { value: "No", icon:<No/>, label: "Norwegia" },
    { value: "Om", icon:<Om/>, label: "Oman" },
    { value: "Pk", icon:<Pk/>, label: "Pakistan" },
    { value: "Pw", icon:<Pw/>, label: "Palau" },
    { value: "Ps", icon:<Ps/>, label: "Palestyna" },
    { value: "Pa", icon:<Pa/>, label: "Panama" },
    { value: "Pg", icon:<Pg/>, label: "Papua-Nowa Gwinea" },
    { value: "Py", icon:<Py/>, label: "Paragwaj" },
    { value: "Pe", icon:<Pe/>, label: "Peru" },
    { value: "Ph", icon:<Ph/>, label: "Filipiny" },
    { value: "Pn", icon:<Pn/>, label: "Pitcairn" },
    { value: "Pl", icon:<Pl/>, label: "Polska" },
    { value: "Pt", icon:<Pt/>, label: "Portugalia" },
    { value: "Pr", icon:<Pr/>, label: "Portoryko" },
    { value: "Qa", icon:<Qa/>, label: "Katar" },
    { value: "Ro", icon:<Ro/>, label: "Rumunia" },
    { value: "Ru", icon:<Ru/>, label: "Rosja" },
    { value: "Rw", icon:<Rw/>, label: "Rwanda" },
    { value: "Kn", icon:<Kn/>, label: "Saint Kitts i Nevis" },
    { value: "Lc", icon:<Lc/>, label: "Saint Lucia" },
    { value: "Ws", icon:<Ws/>, label: "Samoa" },
    { value: "Sm", icon:<Sm/>, label: "San Marino" },
    { value: "St", icon:<St/>, label: "Wyspy Św. Tomasza i Książęca" },
    { value: "Sa", icon:<Sa/>, label: "Arabia Saudyjska" },
    { value: "Sn", icon:<Sn/>, label: "Senegal" },
    { value: "Rs", icon:<Rs/>, label: "Serbia" },
    { value: "Sc", icon:<Sc/>, label: "Seszele" },
    { value: "Sl", icon:<Sl/>, label: "Sierra Leone" },
    { value: "Sg", icon:<Sg/>, label: "Singapur" },
    { value: "Sx", icon:<Sx/>, label: "Sint Maarten" },
    { value: "Sk", icon:<Sk/>, label: "Słowacja" },
    { value: "Si", icon:<Si/>, label: "Słowenia" },
    { value: "Sb", icon:<Sb/>, label: "Wyspy Salomona" },
    { value: "So", icon:<So/>, label: "Somalia" },
    { value: "Za", icon:<Za/>, label: "Rep. Południowej Afryki" },
    { value: "Ss", icon:<Ss/>, label: "Sudan Południowy" },
    { value: "Es", icon:<Es/>, label: "Hiszpania" },
    { value: "Lk", icon:<Lk/>, label: "Sri Lanka" },
    { value: "Sd", icon:<Sd/>, label: "Sudan" },
    { value: "Sr", icon:<Sr/>, label: "Surinam" },
    { value: "Sz", icon:<Sz/>, label: "Suazi" },
    { value: "Se", icon:<Se/>, label: "Szwecja" },
    { value: "Ch", icon:<Ch/>, label: "Szwajcaria" },
    { value: "Sy", icon:<Sy/>, label: "Syria" },
    { value: "Tw", icon:<Tw/>, label: "Tajwan" },
    { value: "Tj", icon:<Tj/>, label: "Tadżykistann" },
    { value: "Tz", icon:<Tz/>, label: "Tanzania" },
    { value: "Th", icon:<Th/>, label: "Tajlandia" },
    { value: "Tg", icon:<Tg/>, label: "Togo" },
    { value: "Tk", icon:<Tk/>, label: "Tokelau" },
    { value: "To", icon:<To/>, label: "Tonga" },
    { value: "Tt", icon:<Tt/>, label: "Trynidad i Tobago" },
    { value: "Tn", icon:<Tn/>, label: "Tunezja" },
    { value: "Tr", icon:<Tr/>, label: "Turcja" },
    { value: "Tm", icon:<Tm/>, label: "Turkmenistan" },
    { value: "Tc", icon:<Tc/>, label: "Wyspy Turks i Caicos" },
    { value: "Tv", icon:<Tv/>, label: "Tuvalu" },
    { value: "Ug", icon:<Ug/>, label: "Uganda" },
    { value: "Ua", icon:<Ua/>, label: "Ukraina" },
    { value: "Ae", icon:<Ae/>, label: "Zjedn. Emiraty Arabskie" },
    { value: "Gb", icon:<Gb/>, label: "Wielka Brytania" },
    { value: "Us", icon:<Us/>, label: "Stany Zjednoczone" },
    { value: "Uy", icon:<Uy/>, label: "Urugwaj" },
    { value: "Uz", icon:<Uz/>, label: "Uzbekistan" },
    { value: "Vu", icon:<Vu/>, label: "Vanuatu" },
    { value: "Ve", icon:<Ve/>, label: "Wenezuela" },
    { value: "Vn", icon:<Vn/>, label: "Wietnam" },
    { value: "Vi", icon:<Vi/>, label: "Wyspy Dziewicze" },
    { value: "Ye", icon:<Ye/>, label: "Jemen" },
    { value: "Zm", icon:<Zm/>, label: "Zambia" },
    { value: "Zw", icon:<Zw/>, label: "Zimbabwe" },
  ];

export default { flags };