import { Link } from '@inertiajs/inertia-react';
import React, { useState } from "react";
import ReactFlagsSelect from "react-flags-select";


export default function FlagSelector ({}) {
  const [selected, setSelected] = useState("");

    return (
    <>

   <ReactFlagsSelect
    selected={selected}
    onSelect={(code) => setSelected(code)}
    placeholder="Nie wybrano kraju"
    selectedSize={14}
    optionsSize={13}
    searchable
    fullWidth    
    className="flex-grow-1 p-0 m-0 ms-n1"
    selectButtonClassName="border-start-0 rounded-0 rounded-end text-wrap border-light"
    customLabels={{ 

      AF: "Afganistan",
      AL: "Albania",
      DZ: "Algeria",
      AS: "Samoa Amerykańskie",
      AD: "Andora",
      AO: "Angola",
      AI: "Anguilla",
      AG: "Antigua i Barbuda",
      AR: "Argentyna",
      AM: "Armenia",
      AW: "Aruba",
      AU: "Australia",
      AT: "Austria",
      AZ: "Azerbejdżan",
      BS: "Bahamy",
      BH: "Bahrajn",
      BD: "Bangladesz",
      BB: "Barbados",
      BY: "Białoruś",
      BE: "Belgia",
      BZ: "Belize",
      BJ: "Benin",
      BM: "Bermudy",
      BT: "Bhutan",
      BO: "Boliwia",
      BA: "Bośnia i Hercegowina",
      BW: "Botswana",
      BR: "Brazylia",
      IO: "Brytyjskie Teryt. O. Indyjsk.",
      BG: "Bułgaria",
      BF: "Burkina Faso",
      BI: "Burundi",
      KH: "Kambodża",
      CM: "Kamerun",
      CA: "Kanada",
      CV: "Zielony Przylądek",
      KY: "Kajmany",
      CF: "Rep. Środkowoafrykańska",
      TD: "Czad",
      CL: "Chile",
      CN: "Chiny",
      CO: "Kolumbia",
      KM: "Komory",
      CG: "Kongo",
      CD: "Rep. Demokratyczna Kongo",
      CK: "Wyspy Cooka",
      CR: "Kostaryka",
      CI: "Wybrzeże Kości Słoniowej",
      HR: "Chorwacja",
      CU: "Kuba",
      CW: "Kurakao",
      CY: "Cypr",
      CZ: "Czechy",
      DK: "Dania",
      DJ: "Dżibuti",
      DM: "Dominika",
      DO: "Dominikana",
      EC: "Ekwador",
      EG: "Egipt",
      SV: "Salwador",
      GQ: "Gwinea Równikowa",
      ER: "Erytrea",
      EE: "Estonia",
      ET: "Etiopia",
      FK: "Falklandy",
      FO: "Wyspy Owcze",
      FJ: "Fidżi",
      FI: "Finlandia",
      FR: "Francja",
      PF: "Polinezja Francuska",
      GA: "Gabon",
      GM: "Gambia",
      GE: "Gruzja",
      DE: "Niemcy",
      GH: "Ghana",
      GI: "Gibraltar",
      GR: "Grecja",
      GL: "Grenlandia",
      GD: "Grenada",
      GU: "Guam",
      GT: "Gwatemala",
      GG: "Guernsey",
      GN: "Gwinea",
      GW: "Gwinea-Bissau",
      HT: "Haiti",
      HN: "Honduras",
      HK: "Hongkong",
      HU: "Węgry",
      IS: "Islandia",
      IN: "Indie",
      ID: "Indonezja",
      IR: "Iran",
      IQ: "Irak",
      IE: "Irlandia",
      IM: "Isle of Man",
      IL: "Izrael",
      IT: "Włochy",
      JM: "Jamajka",
      JP: "Japonia",
      JE: "Jersey",
      JO: "Jordania",
      KZ: "Kazachstan",
      KE: "Kenia",
      KI: "Kiribati",
      KP: "Korea Północna",
      KR: "Korea Południowa",
      KW: "Kuwejt",
      KG: "Kirgistan",
      LA: "Laos",
      LV: "Łotwa",
      LB: "Liban",
      LS: "Lesotho",
      LR: "Liberia",
      LY: "Libia",
      LI: "Liechtenstein",
      LT: "Litwa",
      LU: "Luksemburg",
      MO: "Makau",
      MK: "Macedonia Północna",
      MG: "Madagaskar",
      MW: "Malawi",
      MY: "Malezja",
      MV: "Malediwy",
      ML: "Mali",
      MT: "Malta",
      MH: "Wyspy Marshalla",
      MQ: "Martynikae",
      MR: "Mauretania",
      MU: "Mauritius",
      MX: "Meksyk",
      FM: "Mikronezja",
      MD: "Mołdawia",
      MC: "Monako",
      MN: "Mongolia",
      ME: "Czarnogóra",
      MS: "Montserrat",
      MA: "Maroko",
      MZ: "Mozambik",
      MM: "Myanmar",
      NA: "Namibia",
      NR: "Nauru",
      NP: "Nepal",
      NL: "Holandia",
      NZ: "Nowa Zelandia",
      NI: "Nikaragua",
      NE: "Niger",
      NG: "Nigeria",
      NU: "Niue",
      NF: "Norfolk",
      MP: "Mariany Północne",
      NO: "Norwegia",
      OM: "Oman",
      PK: "Pakistan",
      PW: "Palau",
      PS: "Palestyna",
      PA: "Panama",
      PG: "Papua-Nowa Gwinea",
      PY: "Paragwaj",
      PE: "Peru",
      PH: "Filipiny",
      PN: "Pitcairn",
      PL: "Polska",
      PT: "Portugalia",
      PR: "Portoryko",
      QA: "Katar",
      RO: "Rumunia",
      RU: "Rosja",
      RW: "Rwanda",
      KN: "Saint Kitts i Nevis",
      LC: "Saint Lucia",
      WS: "Samoa",
      SM: "San Marino",
      ST: "Wyspy Św. Tomasza i Książęca",
      SA: "Arabia Saudyjska",
      SN: "Senegal",
      RS: "Serbia",
      SC: "Seszele",
      SL: "Sierra Leone",
      SG: "Singapur",
      SX: "Sint Maarten",
      SK: "Słowacja",
      SI: "Słowenia",
      SB: "Wyspy Salomona",
      SO: "Somalia",
      ZA: "Rep. Południowej Afryki",
      SS: "Sudan Południowy",
      ES: "Hiszpania",
      LK: "Sri Lanka",
      SD: "Sudan",
      SR: "Surinam",
      SZ: "Suazi",
      SE: "Szwecja",
      CH: "Szwajcaria",
      SY: "Syria",
      TW: "Tajwan",
      TJ: "Tadżykistann",
      TZ: "Tanzania",
      TH: "Tajlandia",
      TG: "Togo",
      TK: "Tokelau",
      TO: "Tonga",
      TT: "Trynidad i Tobago",
      TN: "Tunezja",
      TR: "Turcja",
      TM: "Turkmenistan",
      TC: "Wyspy Turks i Caicos",
      TV: "Tuvalu",
      UG: "Uganda",
      UA: "Ukraina",
      AE: "Zjedn. Emiraty Arabskie",
      GB: "Wielka Brytania",
      US: "Stany Zjednoczone",
      UY: "Urugwaj",
      UZ: "Uzbekistan",
      VU: "Vanuatu",
      VE: "Wenezuela",
      VN: "Wietnam",
      VI: "Wyspy Dziewicze",
      YE: "Jemen",
      ZM: "Zambia",
      ZW: "Zimbabwe",


     }}
  />
    </>
    );
}
